# Generated by Django 5.0.4 on 2024-06-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_content_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
