# Generated by Django 5.0.4 on 2024-06-26 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_task_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_posted',
            new_name='date_due',
        ),
    ]
